version: 0.2

phases: 
    install:
        commands:
            - echo "installing something"
            - wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
            - tar xJf Python-3.6.0.tar.xz
            - cd Python-3.6.0
            - ./configure
            - make
            - make install
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
             - python3 -V
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
            
