version: 0.2

phases: 
    install:
        runtime-versions:
            python: 3.7
        commands:
            - echo "installing something"
            - "cd /usr/bin"
            - "curl -O https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip"
            - "unzip terraform_0.12.29_linux_amd64.zip"
            - pip install boto3
            - pip install awscli
            - pip show boto3
            - aws --version
            - terraform -v
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
            - python3 -V
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
            
